// Seed data extracted from Tactical_Plan.xlsx — 'Master sheet' A2:O98 (97 rows).
// Column order in the workbook: Imperative, CSF, Tactical Initiative, Function, Tactic,
// Deliverable(s), Category, Subcategory, Priority, Status, Start_date, End_date, Lead, Budget, Comments.
const SEED_DATA = [
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Develop Center of Excellence educational plan",
  "function": "Medical Affairs",
  "tactic": "Peer-to-peer medical content",
  "deliverable": "Approved content",
  "category": "KOL amplification",
  "subcategory": "Speaker programs",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.2",
  "initiative": "Optimize KOL engagement",
  "function": "Medical Affairs",
  "tactic": "KOL mapping",
  "deliverable": "KOL map",
  "category": "KOL amplification",
  "subcategory": "",
  "priority": "Must do",
  "status": "Initiated",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.2",
  "initiative": "Optimize KOL engagement",
  "function": "Medical Affairs",
  "tactic": "Medical Ad boards",
  "deliverable": "Ad Board materials",
  "category": "KOL amplification",
  "subcategory": "Speaker programs",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.2",
  "initiative": "Optimize KOL engagement",
  "function": "Medical Affairs",
  "tactic": "Metrics development",
  "deliverable": "Metrics",
  "category": "KOL amplification",
  "subcategory": "KOL advocacy",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.2",
  "initiative": "Optimize KOL engagement",
  "function": "Medical Affairs",
  "tactic": "Medical Round Table",
  "deliverable": "Discussion guide",
  "category": "KOL amplification",
  "subcategory": "Speaker programs",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.2",
  "initiative": "Optimize KOL engagement",
  "function": "Medical Affairs",
  "tactic": "Journal Clubs",
  "deliverable": "Discussion guide",
  "category": "KOL amplification",
  "subcategory": "KOL advocacy",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Develop & deliver peer-reviewed data",
  "function": "Medical Affairs",
  "tactic": "Publication planning",
  "deliverable": "Publications plan",
  "category": "Evidence engine",
  "subcategory": "Publications",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "GLOBAL",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Develop & deliver peer-reviewed data",
  "function": "Medical Affairs",
  "tactic": "Publication execution",
  "deliverable": "Peer-reviewed journal articles (#)",
  "category": "Evidence engine",
  "subcategory": "Publications",
  "priority": "Should do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "GLOBAL",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.2",
  "initiative": "Develop & deliver peer-reviewed data",
  "function": "Medical Affairs",
  "tactic": "Poster presentations",
  "deliverable": "Congress abstracts and posters (#)",
  "category": "Evidence engine",
  "subcategory": "Abstracts",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.1",
  "initiative": "Create Peer-to-peer content",
  "function": "Medical Affairs",
  "tactic": "Scientific Message Platform",
  "deliverable": "Needs assessment template",
  "category": "",
  "subcategory": "",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.1",
  "initiative": "Create Peer-to-peer content",
  "function": "Medical Affairs",
  "tactic": "Scientific Message Platform",
  "deliverable": "Scientific message platform",
  "category": "",
  "subcategory": "",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.2",
  "initiative": "Create Peer-to-peer content",
  "function": "Medical Affairs",
  "tactic": "Whitepapers (#)",
  "deliverable": "Whitepaper manuscripts",
  "category": "Evidence engine",
  "subcategory": "Publications",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.2",
  "initiative": "Create Peer-to-peer content",
  "function": "Medical Affairs",
  "tactic": "Academic Center presentations",
  "deliverable": "Slide deck(s)",
  "category": "KOL amplification",
  "subcategory": "KOL advocacy",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.1",
  "initiative": "Create Peer-to-peer content",
  "function": "Medical Affairs",
  "tactic": "Peer-to-peer educational materials",
  "deliverable": "Slide decks(s)",
  "category": "KOL amplification",
  "subcategory": "KOL advocacy",
  "priority": "Should do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.3",
  "initiative": "Create Peer-to-peer content",
  "function": "Medical Affairs",
  "tactic": "Peer-to-peer educational materials",
  "deliverable": "Case-based content",
  "category": "KOL amplification",
  "subcategory": "KOL advocacy",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.1",
  "initiative": "Optimize congress opportunities",
  "function": "Medical Affairs",
  "tactic": "Ongoing scientific exchange",
  "deliverable": "RTEs and Slide decks",
  "category": "KOL amplification",
  "subcategory": "KOL advocacy",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Optimize congress opportunities",
  "function": "Medical Affairs",
  "tactic": "Medical Information booth",
  "deliverable": "RWE and Disease state material",
  "category": "KOL amplification",
  "subcategory": "KOL advocacy",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.2",
  "initiative": "Optimize congress opportunities",
  "function": "Medical Affairs",
  "tactic": "Symposium",
  "deliverable": "Slides",
  "category": "KOL amplification",
  "subcategory": "Speaker programs",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.3",
  "initiative": "Optimize congress opportunities",
  "function": "Medical Affairs",
  "tactic": "Congress summaries (internal)",
  "deliverable": "Congress reports",
  "category": "",
  "subcategory": "",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.3",
  "initiative": "Optimize congress opportunities",
  "function": "Medical Affairs",
  "tactic": "Congress calendar and needs assessment",
  "deliverable": "Priority list; needs assessment report",
  "category": "KOL amplification",
  "subcategory": "KOL advocacy",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Support third-party engagement",
  "function": "Medical Affairs",
  "tactic": "CME programming",
  "deliverable": "Calendar and topic list",
  "category": "KOL amplification",
  "subcategory": "CME",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Support third-party engagement",
  "function": "Medical Affairs",
  "tactic": "Paid media",
  "deliverable": "Calendar and topic list",
  "category": "KOL amplification",
  "subcategory": "KOL advocacy",
  "priority": "Should do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.3",
  "initiative": "Generate real-world evidence",
  "function": "Medical Affairs",
  "tactic": "Integrated evidence-generation plan",
  "deliverable": "IEGP  document",
  "category": "Evidence engine",
  "subcategory": "Studies/IISs",
  "priority": "Should do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.1",
  "initiative": "Generate real-world evidence",
  "function": "Medical Affairs",
  "tactic": "Develop evidence generation roster",
  "deliverable": "Evidence generation plan and tracker",
  "category": "Evidence engine",
  "subcategory": "Studies/IISs",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.3",
  "initiative": "Generate real-world evidence",
  "function": "Medical Affairs",
  "tactic": "Investigator-initiated studies",
  "deliverable": "SOP",
  "category": "Evidence engine",
  "subcategory": "Studies/IISs",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Support MSL role",
  "function": "Medical Affairs",
  "tactic": "MSL territory map",
  "deliverable": "Territories list and staffing plan",
  "category": "Field execution",
  "subcategory": "Execution",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Support MSL role",
  "function": "Medical Affairs",
  "tactic": "MSL training and onboarding",
  "deliverable": "Training materials",
  "category": "Field execution",
  "subcategory": "Execution",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.1",
  "initiative": "Develop and enhance value proposition",
  "function": "Access",
  "tactic": "Launch deck",
  "deliverable": "",
  "category": "Fulfillment",
  "subcategory": "Payer access",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.2",
  "initiative": "Develop and enhance value proposition",
  "function": "Access",
  "tactic": "Value dossier",
  "deliverable": "",
  "category": "Fulfillment",
  "subcategory": "Payer access",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.1",
  "initiative": "Develop and enhance value proposition",
  "function": "Access",
  "tactic": "Budget impact model",
  "deliverable": "",
  "category": "Fulfillment",
  "subcategory": "Payer access",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.1",
  "initiative": "Optimize engagement with Payers",
  "function": "Access",
  "tactic": "Payer engagement plan",
  "deliverable": "",
  "category": "Fulfillment",
  "subcategory": "Payer access",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.2",
  "initiative": "Optimize engagement with Payers",
  "function": "Access",
  "tactic": "Payer materials",
  "deliverable": "",
  "category": "Fulfillment",
  "subcategory": "Payer access",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.2",
  "initiative": "Optimize engagement with Payers",
  "function": "Access",
  "tactic": "Payer ad board",
  "deliverable": "",
  "category": "Fulfillment",
  "subcategory": "Payer access",
  "priority": "Should do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": "consider add tactic for CADs to reach out to their contacts within plans and conduct ad hoc insights gathering (dinner, etc) (must do)"
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.1",
  "initiative": "Generate earned media",
  "function": "PR",
  "tactic": "Press releases (#)",
  "deliverable": "",
  "category": "Promotional resources",
  "subcategory": "Digital channels",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.2",
  "initiative": "Train and equip external brand spokes people",
  "function": "PR",
  "tactic": "Spokesperson engagement map",
  "deliverable": "",
  "category": "",
  "subcategory": "",
  "priority": "Should do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.2",
  "initiative": "Train and equip external brand spokes people",
  "function": "PR",
  "tactic": "Training (including compliance training)",
  "deliverable": "",
  "category": "Promotional resources",
  "subcategory": "Training",
  "priority": "Should do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.2",
  "initiative": "Seek and leverage paid media opps",
  "function": "PR",
  "tactic": "Sponsored content",
  "deliverable": "Articles",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Should do",
  "status": "Initiated",
  "start": "",
  "end": "",
  "lead": "Healio",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.2",
  "initiative": "Seek and leverage paid media opps",
  "function": "PR",
  "tactic": "KOL interview",
  "deliverable": "Video only",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Should do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.2",
  "initiative": "Seek and leverage paid media opps",
  "function": "PR",
  "tactic": "Social media amplification",
  "deliverable": "Media posts",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Should do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "GLOBAL with Local support",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Build KAM capabilities and expertise",
  "function": "Sales Operations",
  "tactic": "Advanced training course/selling skills",
  "deliverable": "Training modules",
  "category": "Promotional resources",
  "subcategory": "Training",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Build KAM capabilities and expertise",
  "function": "Sales Operations",
  "tactic": "Advanced training course/selling skills",
  "deliverable": "Objection handler",
  "category": "Promotional resources",
  "subcategory": "Training",
  "priority": "Should do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Build KAM capabilities and expertise",
  "function": "Sales Operations",
  "tactic": "Advanced training course/selling skills",
  "deliverable": "Selling skills module",
  "category": "Promotional resources",
  "subcategory": "Training",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Build KAM capabilities and expertise",
  "function": "Sales Operations",
  "tactic": "Advanced training course/selling skills",
  "deliverable": "Knowledge flashcard",
  "category": "Promotional resources",
  "subcategory": "Training",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Build KAM capabilities and expertise",
  "function": "Sales Operations",
  "tactic": "Advanced training course/selling skills",
  "deliverable": "Sales playbook (use of materials)",
  "category": "Promotional resources",
  "subcategory": "Training",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Build KAM capabilities and expertise",
  "function": "Sales Operations",
  "tactic": "Advanced training course/selling skills",
  "deliverable": "Annotated IVA",
  "category": "Promotional resources",
  "subcategory": "Training",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.1",
  "initiative": "Build KAM capabilities and expertise",
  "function": "Sales Operations",
  "tactic": "Advanced training course/selling skills",
  "deliverable": "Payer environment training",
  "category": "Promotional resources",
  "subcategory": "Training",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Build KAM capabilities and expertise",
  "function": "Sales Operations",
  "tactic": "Ongoing training and development",
  "deliverable": "Quarterly business plan",
  "category": "",
  "subcategory": "",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.1",
  "initiative": "Build KAM capabilities and expertise",
  "function": "Sales Operations",
  "tactic": "Ongoing training and development",
  "deliverable": "Post-congress updates",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.1",
  "initiative": "Build KAM capabilities and expertise",
  "function": "Sales Operations",
  "tactic": "Ongoing training and development",
  "deliverable": "Post ad-board updates",
  "category": "Promotional resources",
  "subcategory": "Digital channels",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.3",
  "initiative": "Build KAM capabilities and expertise",
  "function": "Sales Operations",
  "tactic": "Ongoing training and development",
  "deliverable": "Scenario-based case studies",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Deliver sales and market data insights",
  "function": "Sales Operations",
  "tactic": "Dashboard creation and validation",
  "deliverable": "Dashboard",
  "category": "Field execution",
  "subcategory": "Tracking",
  "priority": "Should do",
  "status": "Initiated",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Deliver sales and market data insights",
  "function": "Sales Operations",
  "tactic": "Dashboard population and maintenance",
  "deliverable": "Data population",
  "category": "Field execution",
  "subcategory": "Tracking",
  "priority": "Should do",
  "status": "Initiated",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Establish compliant cross-functional rules of engagement",
  "function": "Sales Operations",
  "tactic": "MSL-KAM-corporate rules of engagement",
  "deliverable": "SOP",
  "category": "Field execution",
  "subcategory": "Execution",
  "priority": "Must do",
  "status": "Initiated",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Establish compliant cross-functional rules of engagement",
  "function": "Sales Operations",
  "tactic": "HSSA engagement report template and training",
  "deliverable": "Template and guidance",
  "category": "Field execution",
  "subcategory": "Execution",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Optimize KAM national coverage",
  "function": "Sales Operations",
  "tactic": "Define targets, reach and frequency",
  "deliverable": "Territory plan",
  "category": "Field execution",
  "subcategory": "Execution",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Optimize KAM national coverage",
  "function": "Sales Operations",
  "tactic": "Optimize target list within centers of excellence",
  "deliverable": "Call plan",
  "category": "Field execution",
  "subcategory": "Execution",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Develop KAM incentive plan",
  "function": "Sales Operations",
  "tactic": "Incentive plan",
  "deliverable": "",
  "category": "Field execution",
  "subcategory": "Execution",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.1",
  "initiative": "Reach patients with clear and effective messaging/content Promotional plan",
  "function": "Patient promotional",
  "tactic": "Patient materials",
  "deliverable": "Patient brochure",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Must do",
  "status": "Complete",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.1",
  "initiative": "Reach patients with clear and effective messaging/content Promotional plan",
  "function": "Patient promotional",
  "tactic": "Patient materials",
  "deliverable": "Reimbursement materials",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.3",
  "initiative": "Drive early experience of TRYVIO",
  "function": "Patient promotional",
  "tactic": "",
  "deliverable": "Patient testimonials",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Must do",
  "status": "Initiated",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.3",
  "initiative": "Ensure end-to-end patient support",
  "function": "Patient promotional",
  "tactic": "Update all promotional materials",
  "deliverable": "",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.3",
  "initiative": "Ensure end-to-end patient support",
  "function": "Patient promotional",
  "tactic": "Branding and messaging development",
  "deliverable": "",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Optimize congress opportunities",
  "function": "HCP promotional",
  "tactic": "Congress plan",
  "deliverable": "Congress calendar",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Must do",
  "status": "Initiated",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Optimize congress opportunities",
  "function": "HCP promotional",
  "tactic": "Congress plan",
  "deliverable": "Needs assessment template",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Optimize congress opportunities",
  "function": "HCP promotional",
  "tactic": "Individual national congress #1 (e.g. ACC)",
  "deliverable": "Booth design and development",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Optimize congress opportunities",
  "function": "HCP promotional",
  "tactic": "Individual national congress #1 (e.g. ACC)",
  "deliverable": "Collateral material",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Must do",
  "status": "Complete",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Optimize congress opportunities",
  "function": "HCP promotional",
  "tactic": "Local/regional congress engagement",
  "deliverable": "Exhibit materials",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.1",
  "initiative": "Activate institutional programing",
  "function": "HCP promotional",
  "tactic": "Branded Speaker Programs",
  "deliverable": "Speaker deck, invites, follow-ups",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.1",
  "initiative": "Drive Rx through Personal promotion",
  "function": "HCP promotional",
  "tactic": "Rep-delivered promotional materials",
  "deliverable": "IVA refresh",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Should do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.2",
  "initiative": "Drive Rx through Personal promotion",
  "function": "HCP promotional",
  "tactic": "Rep-delivered promotional materials",
  "deliverable": "Rep-triggered emails",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Should do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.3",
  "initiative": "Drive Rx through Personal promotion",
  "function": "HCP promotional",
  "tactic": "Rep-delivered promotional materials",
  "deliverable": "Flashcards/leave-behinds",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Should do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.1",
  "initiative": "Drive Rx through Personal promotion",
  "function": "HCP promotional",
  "tactic": "MOA video",
  "deliverable": "Video",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.2",
  "initiative": "Drive consideration and awareness through Non-Personal promotion",
  "function": "HCP promotional",
  "tactic": "Non-personal/media materials",
  "deliverable": "Banners",
  "category": "Promotional resources",
  "subcategory": "Digital channels",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.1",
  "initiative": "Drive consideration and awareness through Non-Personal promotion",
  "function": "HCP promotional",
  "tactic": "Non-personal/media materials",
  "deliverable": "HCP website future refresh",
  "category": "Promotional resources",
  "subcategory": "Digital channels",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.1",
  "initiative": "Drive consideration and awareness through Non-Personal promotion",
  "function": "HCP promotional",
  "tactic": "Non-personal/media materials",
  "deliverable": "Media plan",
  "category": "Promotional resources",
  "subcategory": "Digital channels",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.2",
  "initiative": "Drive consideration and awareness through Non-Personal promotion",
  "function": "HCP promotional",
  "tactic": "Non-personal/media materials",
  "deliverable": "Patient testimonial videos (1x)",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.3",
  "initiative": "Drive consideration and awareness through Non-Personal promotion",
  "function": "HCP promotional",
  "tactic": "Non-personal/media materials",
  "deliverable": "HCP testimonial videos (1x)",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.1",
  "initiative": "Drive consideration and awareness through Non-Personal promotion",
  "function": "HCP promotional",
  "tactic": "Non-personal/media materials",
  "deliverable": "Owned media",
  "category": "Promotional resources",
  "subcategory": "Branded content",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.3",
  "initiative": "Maximize potential of patient services Hub",
  "function": "Patient services",
  "tactic": "Identify and onboard Hub provider",
  "deliverable": "RFP",
  "category": "Fulfillment",
  "subcategory": "PA support/HUB",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.3",
  "initiative": "Maximize potential of patient services Hub",
  "function": "Patient services",
  "tactic": "",
  "deliverable": "Internal evaluation",
  "category": "Fulfillment",
  "subcategory": "PA support/HUB",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.3",
  "initiative": "Maximize potential of patient services Hub",
  "function": "Patient services",
  "tactic": "",
  "deliverable": "Transition plan from WAG",
  "category": "Fulfillment",
  "subcategory": "PA support/HUB",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.3",
  "initiative": "Optimize patient support program",
  "function": "Patient services",
  "tactic": "Evaluation",
  "deliverable": "",
  "category": "Fulfillment",
  "subcategory": "PA support/HUB",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.3",
  "initiative": "Optimize patient support program",
  "function": "Patient services",
  "tactic": "Update all marketing materials",
  "deliverable": "",
  "category": "Fulfillment",
  "subcategory": "PA support/HUB",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.3",
  "initiative": "Optimize patient support program",
  "function": "Patient services",
  "tactic": "Evaluate co-pay assistance options",
  "deliverable": "",
  "category": "Fulfillment",
  "subcategory": "PA support/HUB",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.3",
  "initiative": "Optimize distribution process",
  "function": "Patient services",
  "tactic": "Evaluate ecosystem outside of SP",
  "deliverable": "",
  "category": "Fulfillment",
  "subcategory": "PA support/HUB",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.3",
  "initiative": "Optimize distribution process",
  "function": "Patient services",
  "tactic": "Evaluate ANDA/Prasco model",
  "deliverable": "",
  "category": "Fulfillment",
  "subcategory": "PA support/HUB",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.3",
  "initiative": "Maintain organizational awareness of competitors",
  "function": "Market Research",
  "tactic": "Congress CI activities",
  "deliverable": "",
  "category": "Field execution",
  "subcategory": "Tracking",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI2",
  "csf": "CSF 2.3",
  "initiative": "Maintain organizational awareness of competitors",
  "function": "Market Research",
  "tactic": "Literature/media review (ongoing)",
  "deliverable": "",
  "category": "Field execution",
  "subcategory": "Tracking",
  "priority": "Nice-to-have",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI3",
  "csf": "CSF 3.3",
  "initiative": "Gain insights into HTN Patients",
  "function": "Market Research",
  "tactic": "Patient journey research",
  "deliverable": "",
  "category": "Field execution",
  "subcategory": "Tracking",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.2",
  "initiative": "Gain insights into HCP prescribing and behavior",
  "function": "Market Research",
  "tactic": "Quarterly ATU",
  "deliverable": "ATU screener and execution",
  "category": "Field execution",
  "subcategory": "Tracking",
  "priority": "Must do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "SI1",
  "csf": "CSF 1.2",
  "initiative": "HCP research",
  "function": "Market Research",
  "tactic": "Message testing",
  "deliverable": "",
  "category": "Field execution",
  "subcategory": "Tracking",
  "priority": "Should do",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "",
  "csf": "",
  "initiative": "",
  "function": "Digital",
  "tactic": "",
  "deliverable": "",
  "category": "",
  "subcategory": "",
  "priority": "",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "",
  "csf": "",
  "initiative": "",
  "function": "Digital",
  "tactic": "",
  "deliverable": "",
  "category": "",
  "subcategory": "",
  "priority": "",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "",
  "csf": "",
  "initiative": "",
  "function": "Digital",
  "tactic": "",
  "deliverable": "",
  "category": "",
  "subcategory": "",
  "priority": "",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "",
  "csf": "",
  "initiative": "",
  "function": "Internal",
  "tactic": "",
  "deliverable": "",
  "category": "",
  "subcategory": "",
  "priority": "",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "",
  "csf": "",
  "initiative": "",
  "function": "Internal",
  "tactic": "",
  "deliverable": "",
  "category": "",
  "subcategory": "",
  "priority": "",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 },
 {
  "imperative": "",
  "csf": "",
  "initiative": "",
  "function": "Internal",
  "tactic": "",
  "deliverable": "",
  "category": "",
  "subcategory": "",
  "priority": "",
  "status": "",
  "start": "",
  "end": "",
  "lead": "",
  "budget": "",
  "comments": ""
 }
];
